### ISSUE TITLE
Update the 'network' bound

### ISSUE THREAD

**Issue by chris-martin** [haskell/network-bsd#10]
The latest version of `network` is `3.1.2.1`; the current bound here is `<3.1.2`.

I'd love to help if I can, but I'm afraid I really don't understand the notes in the cabal file about why this bound is so complicated.

**Comment by kindaro** [comment]
`network < 3.1.2` does not allow `bytestring 0.11`. So I cannot depend on both `network-bsd` and the new `bytestring` in the same package. This is rather unfortunate.

**Comment by gbaz** [comment]
revision published https://github.com/haskell-infra/hackage-trustees/issues/308
