### ISSUE TITLE
allow network-3.1.2

### ISSUE THREAD

**Issue by juhp** [haskell/network-bsd#13]
See commercialhaskell/stackage#5587

network-3.1.2.1 ([changelog](http://hackage.haskell.org/package/network-3.1.2.1/changelog)) (Grandfathered dependencies, Stackage upper bounds) is out of bounds for:
- [ ] network-bsd-2.8.1.0 ((>=3.0.0.0 && < 3.0.2) || (>=3.1.0.0 && < 3.1.2)). Grandfathered dependencies. @haskell. Used by: library

This is blocking for example Stackage Nightly from moving to network-3.1.2, since various packages depend on network-bsd.

**Comment by ysangkok** [comment]
It looks like `network-bsd` was simply removed from Stackage. So is it no longer blocking Stackage from upgrading `network`? Trying to interpret [the recently merged commit bumping network](https://github.com/commercialhaskell/stackage/commit/c9f3a908d4915a420989f98cde4e0332515ab087).

**Comment by juhp** [comment]
Well we are updating Stackage Nightly right now to ghc-9.0 and at the same time lifting most upperbounds and pruning packages that can't be satisfied... (including network-bsd).

**Comment by gbaz** [comment]
revision published: https://github.com/haskell-infra/hackage-trustees/issues/308

**Comment by juhp** [comment]
It should re-appear in the next Stackage Nightly snapshot.
