### ISSUE TITLE
Relax upper bound for network (stackage nightly)

### ISSUE THREAD

**Issue by PierreR** [haskell/network-bsd#6]
`network-bsd` is currently out of stackage nightly because of its upper bound for network.

It prevents `hslogger` to be in stackage nightly together with all packages that depend on it. 

Would it be possible to use a caret upper-bound in order to allow `network-3.1.1.0`, something alike `network >= 3.0.0.0 && ^>= 3.2` ?

**Comment by kazu-yamamoto** [comment]
@PierreR Probably Herbert does not notice notifications from github.
I would like to recommend you to ping to `@hvrgnu` on Twitter.

**Comment by PierreR** [comment]
@kazu-yamamoto Thanks ! I am not able to send him a message on Twitter. I have got:
```
@hvrgnu can’t be messaged
```
I might just go for another logger if I find the time.

**Comment by hvr** [comment]
I've reviewed the API changes and deemed them harmless enough to effect a revision at http://hackage.haskell.org/package/network-bsd-2.8.1.0/revisions/

(For future ref: you can reach me more effectively via gmail, discord or IRC -- that's how I was made aware of this issue)
